/**
 * Dry-run walkthrough tests for the architecture-change task type.
 *
 * These tests validate:
 * 1. The write scope boundaries are correctly documented
 * 2. Generated-file prohibition is clear
 * 3. ADR requirement is enforceable
 * 4. Human approval gate is documented
 *
 * Since this is an agent-contract story (not runtime code), these tests
 * verify document structure and content correctness rather than executing
 * runtime logic.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";

const ROOT = resolve(__dirname, "../..");

function readFile(path: string): string {
  return readFileSync(resolve(ROOT, path), "utf-8");
}

describe("architecture-change — write scope validation", () => {
  const agents = readFile("AGENTS.md");

  it("explicitly lists all allowed files for modification", () => {
    // Must mention all 5 allowed paths
    const allowedPaths = [
      "architecture.md",
      "domains.md",
      "glossary.md",
      "conventions.md",
      "catalog/flows/",
    ];
    for (const path of allowedPaths) {
      expect(agents).toContain(path);
    }
  });

  it("explicitly prohibits catalog/components/*.json editing", () => {
    // The prohibition must be clear and unambiguous
    expect(agents).toMatch(/catalog\/components\/\*\.json.*never hand-edited or agent-edited/s);
  });

  it("explicitly prohibits catalog/index.yaml editing", () => {
    expect(agents).toMatch(/catalog\/index\.yaml.*never hand-edited or agent-edited/s);
  });

  it("states that generated files come from CI pipelines", () => {
    expect(agents).toContain("generated by CI");
    expect(agents).toContain("dt extract");
    expect(agents).toContain("dt catalog build");
  });
});

describe("architecture-change — ADR requirement validation", () => {
  const agents = readFile("AGENTS.md");

  it("requires ADR before opening a meta-repo PR", () => {
    expect(agents).toMatch(
      /Before opening any meta-repo PR.*MUST.*produce an Architecture Decision Record/s,
    );
  });

  it("ADR must contain all four required sections", () => {
    const adrSection = agents.slice(
      agents.indexOf("#### ADR Requirement"),
      agents.indexOf("#### Human Approval Gate"),
    );
    expect(adrSection).toContain("Context");
    expect(adrSection).toContain("Decision");
    expect(adrSection).toContain("Consequences");
    expect(adrSection).toContain("Alternatives considered");
  });

  it("ADR must be committed as part of the PR", () => {
    expect(agents).toContain("committed as part of the PR");
  });
});

describe("architecture-change — human approval gate validation", () => {
  const agents = readFile("AGENTS.md");

  it("requires explicit human review for meta-repo PRs", () => {
    expect(agents).toContain("explicit human review and approval");
  });

  it("prohibits auto-merge", () => {
    expect(agents).toContain("No agent may auto-merge");
    expect(agents).toContain("architecture-change");
  });

  it("aligns with existing branch/PR discipline", () => {
    expect(agents).toContain("PRs targeting `main` require user approval");
  });
});

describe("architecture-change — exclusion rule enforcement", () => {
  const agents = readFile("AGENTS.md");

  it("defines the refusal message for unauthorized writes", () => {
    expect(agents).toContain("Meta-repo writes require the `architecture-change` task type");
  });

  it("applies to all agents", () => {
    expect(agents).toContain("`product-engineer`");
    expect(agents).toContain("`developer`");
    expect(agents).toContain("`planner`");
    expect(agents).toContain("`housekeeping`");
  });
});

describe("architecture-change — attempt to edit index.yaml outside task type → refused", () => {
  // Simulates checking that the developer agent would refuse
  const developerKiro = readFile(".kiro/agents/developer.md");

  it("developer must stop and inform user when meta-repo write is needed", () => {
    expect(developerKiro).toContain(
      "MUST** stop and inform the user that an `architecture-change` task is required",
    );
  });

  it("developer references generated-file prohibition", () => {
    expect(developerKiro).toContain("`catalog/components/*.json`");
    expect(developerKiro).toContain("`catalog/index.yaml`");
    expect(developerKiro).toContain("generated by CI");
    expect(developerKiro).toContain("MUST** never be modified directly");
  });
});

describe("architecture-change — attempt without ADR → blocked", () => {
  const agents = readFile("AGENTS.md");

  it("ADR is mandatory (MUST) not optional (SHOULD)", () => {
    // Extract the ADR section and verify MUST language
    const adrSection = agents.slice(
      agents.indexOf("#### ADR Requirement"),
      agents.indexOf("#### Human Approval Gate"),
    );
    expect(adrSection).toContain("**MUST**");
  });
});

describe("architecture-change — attempt to auto-merge → blocked", () => {
  const agents = readFile("AGENTS.md");

  it("auto-merge is explicitly prohibited with MUST NOT equivalent", () => {
    expect(agents).toContain("No agent may auto-merge");
  });

  it("human approval is REQUIRE level", () => {
    expect(agents).toContain("**REQUIRE** explicit human review");
  });
});
