/**
 * Structural parity check: verifies that the architecture-change task type
 * documentation is consistent across all three platform trees.
 *
 * This test ensures that the meta-repo write restriction (RF-64), ADR requirement,
 * human approval gate, and generated-file prohibition are documented consistently
 * across .kiro/, .github/, and .claude/ trees for all relevant agents.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";

const ROOT = resolve(__dirname, "../..");

function readAgent(path: string): string {
  return readFileSync(resolve(ROOT, path), "utf-8");
}

describe("architecture-change task type — AGENTS.md", () => {
  const agents = readAgent("AGENTS.md");

  it("defines the architecture-change task type section", () => {
    expect(agents).toContain("### architecture-change");
  });

  it("documents allowed write scope (RF-62)", () => {
    expect(agents).toContain("`architecture.md`");
    expect(agents).toContain("`domains.md`");
    expect(agents).toContain("`glossary.md`");
    expect(agents).toContain("`conventions.md`");
    expect(agents).toContain("`catalog/flows/`");
  });

  it("documents prohibited files", () => {
    expect(agents).toContain("`catalog/components/*.json`");
    expect(agents).toContain("`catalog/index.yaml`");
  });

  it("documents generated-file prohibition", () => {
    expect(agents).toContain("Generated-File Prohibition");
    expect(agents).toContain("generated by CI");
    expect(agents).toContain("never hand-edited or agent-edited");
  });

  it("documents ADR requirement", () => {
    expect(agents).toContain("ADR Requirement");
    expect(agents).toContain("Architecture Decision Record");
    expect(agents).toContain("Context");
    expect(agents).toContain("Decision");
    expect(agents).toContain("Consequences");
    expect(agents).toContain("Alternatives considered");
  });

  it("documents human approval gate", () => {
    expect(agents).toContain("Human Approval Gate");
    expect(agents).toContain("explicit human review and approval");
    expect(agents).toContain("No agent may auto-merge");
  });

  it("documents exclusion rule (RF-64)", () => {
    expect(agents).toContain("Exclusion Rule (RF-64)");
    expect(agents).toContain(
      "MUST NOT** write to the meta-repo outside the `architecture-change` task type",
    );
  });
});

describe("architecture-change task type — product-engineer parity", () => {
  const kiro = readAgent(".kiro/agents/product-engineer.md");
  const github = readAgent(".github/agents/product-engineer.agent.md");
  const claude = readAgent(".claude/commands/product-engineer.md");

  const expectedRule =
    "Meta-repo write restriction (RF-64):** You **MUST NOT** write to the meta-repo outside the `architecture-change` task type";

  it("kiro product-engineer contains the meta-repo write restriction", () => {
    expect(kiro).toContain(expectedRule);
  });

  it("github product-engineer contains the meta-repo write restriction", () => {
    expect(github).toContain(expectedRule);
  });

  it("claude product-engineer contains the meta-repo write restriction", () => {
    expect(claude).toContain(expectedRule);
  });

  it("all three trees reference the same allowed files", () => {
    const allowedFiles = [
      "`architecture.md`",
      "`domains.md`",
      "`glossary.md`",
      "`conventions.md`",
      "`catalog/flows/`",
    ];
    for (const file of allowedFiles) {
      expect(kiro).toContain(file);
      expect(github).toContain(file);
      expect(claude).toContain(file);
    }
  });

  it("all three trees reference the generated-file prohibition", () => {
    const prohibitedFiles = ["`catalog/components/*.json`", "`catalog/index.yaml`"];
    for (const file of prohibitedFiles) {
      expect(kiro).toContain(file);
      expect(github).toContain(file);
      expect(claude).toContain(file);
    }
  });
});

describe("architecture-change task type — developer parity", () => {
  const kiro = readAgent(".kiro/agents/developer.md");
  const github = readAgent(".github/agents/developer.agent.md");
  const claudeAgent = readAgent(".claude/agents/developer.md");
  const claudeCmd = readAgent(".claude/commands/developer.md");

  const expectedRule =
    "Meta-repo write restriction (RF-64):** You **MUST NOT** write to the meta-repo outside the `architecture-change` task type";

  it("kiro developer contains the meta-repo write restriction", () => {
    expect(kiro).toContain(expectedRule);
  });

  it("github developer contains the meta-repo write restriction", () => {
    expect(github).toContain(expectedRule);
  });

  it("claude developer agent contains the meta-repo write restriction", () => {
    expect(claudeAgent).toContain(expectedRule);
  });

  it("claude developer command contains the meta-repo write restriction", () => {
    expect(claudeCmd).toContain(expectedRule);
  });
});

describe("architecture-change task type — planner parity", () => {
  const kiro = readAgent(".kiro/agents/planner.md");
  const github = readAgent(".github/agents/planner.agent.md");
  const claude = readAgent(".claude/commands/planner.md");

  const expectedRule =
    "MUST NOT** write to the meta-repo outside the `architecture-change` task type";

  it("kiro planner contains the meta-repo write restriction", () => {
    expect(kiro).toContain(expectedRule);
  });

  it("github planner contains the meta-repo write restriction", () => {
    expect(github).toContain(expectedRule);
  });

  it("claude planner contains the meta-repo write restriction", () => {
    expect(claude).toContain(expectedRule);
  });
});
