/**
 * Structural and behavioral parity checks for the infra-engineer agent.
 *
 * Covers Story S-001 and the file-contract portions of AC-1 through AC-15.
 * The platform variants intentionally share policy language while retaining
 * native frontmatter and entry-point conventions.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "../..");

const COPILOT_AGENT = ".github/agents/infra-engineer.agent.md";
const CLAUDE_AGENT = ".claude/commands/infra-engineer.md";
const KIRO_AGENT = ".kiro/agents/infra-engineer.md";
const COPILOT_ENTRY = ".github/prompts/infra-engineer.prompt.md";
const TEMPLATE = "templates/infra/environments.yaml";

const AGENT_VARIANTS = [COPILOT_AGENT, CLAUDE_AGENT, KIRO_AGENT] as const;
const REQUIRED_FILES = [...AGENT_VARIANTS, COPILOT_ENTRY, TEMPLATE] as const;

/**
 * Planner variants that must name the post-integration deploy handoff to
 * infra-engineer (Story S-009 AC-5b). Full caller wiring for other agents is
 * Story S-010; this block is scoped to planner's deploy handoff only.
 */
const PLANNER_VARIANTS = [
  ".kiro/agents/planner.md",
  ".github/agents/planner.agent.md",
  ".claude/commands/planner.md",
] as const;

/**
 * Registry and documentation files that must register deploy-ops and the
 * workflow templates (Story S-009 AC-5). workflow-chains.md is intentionally
 * excluded here — its deploy-chain content lands in Story S-010 / Task 10.5.
 */
const REGISTRY_FILES = [
  "AGENTS.md",
  "AGENTS.md.template",
  "CLAUDE.md",
  "CLAUDE.md.template",
  "README.md",
  "docs/system-overview.md",
] as const;

/** Normative policy statements required in every platform variant. */
const CONTRACT_STATEMENTS: ReadonlyArray<{ label: string; pattern: RegExp }> = [
  {
    label: "working loop",
    pattern:
      /discover\s*[→>-]\s*plan.*approve plan.*approve step.*backup.*apply.*verify.*record.*result/is,
  },
  { label: "no skippable phase", pattern: /no skippable phase/i },
  {
    label: "ChangeId and per-step approval",
    pattern: /ChangeId.*approval.*step|approval.*ChangeId/is,
  },
  {
    label: "no autonomous or batch mode",
    pattern: /autonomous mode.*batch mode|batch mode.*autonomous mode/is,
  },
  {
    label: "step schema",
    pattern: /kind.*tool.*environment.*forward.*expected result.*verify.*revert.*touches state/is,
  },
  {
    label: "step state machine",
    pattern: /pending.*approved.*backed_up.*applied.*verified.*failed.*reverted.*skipped/is,
  },
  {
    label: "production revert rule",
    pattern: /production.*revert.*refused|production.*no revert.*refus/i,
  },
  { label: "rollback reverse order", pattern: /rollback\.sh.*reverse order/i },
  {
    label: "production backup rule",
    pattern: /production.*touches state.*backup id.*restore command/is,
  },
  { label: "two-tier model", pattern: /foundation.*application/is },
  { label: "ephemeral ExpiresAt", pattern: /ephemeral.*ExpiresAt/is },
  {
    label: "destroy safeguards",
    pattern: /destroy.*(reverse|revers).*environment.*(production|refus|typed)/is,
  },
  { label: "identity assertion", pattern: /identity.*assert|assert.*identity/is },
  {
    label: "platform identity probes",
    pattern: /sts get-caller-identity.*flyctl auth whoami.*supabase projects list/is,
  },
  { label: "tool checks", pattern: /presence.*version floor.*authentication.*remediation/is },
  { label: "no auto-install or fallback", pattern: /no auto-install.*no fallback/is },
  { label: "tool-routing table", pattern: /tool-routing table/is },
  { label: "cost rule", pattern: /monthly estimate.*source.*APPROVAL REQUIRED/is },
  { label: "read-only cost sweep", pattern: /read-only.*cost sweep|cost sweep.*read-only/is },
  { label: "plan record", pattern: /plan\.md.*ChangeId.*environment.*identity/is },
  { label: "commands record", pattern: /commands\.sh.*append-only/is },
  {
    label: "result and inventory records",
    pattern: /result\.md.*_generated.*generated by infra-engineer/is,
  },
  { label: "draft PR handoff", pattern: /draft PR.*github-ops|github-ops.*draft PR/is },
  { label: "tag prohibition", pattern: /never.*create.*move.*delete.*push.*tags/is },
  {
    label: "secret handling",
    pattern: /ARN.*fly secrets.*supabase secrets.*gh secret set.*OIDC/is,
  },
  {
    label: "bounded redacted log triage",
    pattern: /bounded.*UTC.*redaction.*inference.*labelled/is,
  },
  {
    label: "mandatory redaction filter reference",
    pattern: /redaction-patterns\.txt/i,
  },
  {
    label: "raw output never written",
    pattern: /raw output is never (written|persisted)/i,
  },
  {
    label: "Cloudflare DNS and certificates",
    pattern: /Cloudflare.*DNS.*certificate.*prior.*revert/is,
  },
  { label: "template-status block", pattern: /status: template.*missing.*blocks/is },
];

function exists(relativePath: string): boolean {
  return existsSync(resolve(ROOT, relativePath));
}

function read(relativePath: string): string {
  return readFileSync(resolve(ROOT, relativePath), "utf8");
}

function extractFrontmatter(contents: string): string | null {
  if (!contents.startsWith("---\n")) return null;
  const end = contents.indexOf("\n---", 4);
  return end === -1 ? null : contents.slice(4, end + 1);
}

describe("infra-engineer — required files and packaging", () => {
  for (const relativePath of REQUIRED_FILES) {
    it(`ships ${relativePath}`, () => {
      expect(exists(relativePath), `missing required file: ${relativePath}`).toBe(true);
    });
  }

  it("keeps all platform variants non-empty", () => {
    for (const relativePath of AGENT_VARIANTS) {
      expect(read(relativePath).trim(), `${relativePath} is empty`).not.toBe("");
    }
  });

  it("does not ship a Claude agent duplicate", () => {
    expect(exists(".claude/agents/infra-engineer.md")).toBe(false);
  });
});

describe("infra-engineer — behavioral parity", () => {
  for (const statement of CONTRACT_STATEMENTS) {
    it(`declares ${statement.label} in all variants`, () => {
      const missing = AGENT_VARIANTS.filter(
        (relativePath) => !exists(relativePath) || !statement.pattern.test(read(relativePath)),
      );
      expect(
        missing,
        `contract statement "${statement.label}" absent from: ${missing.join(", ")}`,
      ).toEqual([]);
    });
  }
});

describe("infra-engineer — Kiro frontmatter", () => {
  it("declares description, tools, and resources without permissions", () => {
    const frontmatter = extractFrontmatter(read(KIRO_AGENT));
    expect(frontmatter, `${KIRO_AGENT} has no frontmatter`).not.toBeNull();
    expect(frontmatter).toMatch(/^description:/m);
    expect(frontmatter).toMatch(/^tools:\s*\[read, write, shell\]/m);
    expect(frontmatter).toMatch(/^resources:/m);
    expect(frontmatter).not.toMatch(/^permissions:/m);
  });
});

describe("infra-engineer — template status guard", () => {
  it("starts the environment template with the status sentinel", () => {
    expect(read(TEMPLATE).split("\n", 1)[0]).toBe("# status: template");
  });

  it("states that a template-status file blocks work", () => {
    for (const relativePath of AGENT_VARIANTS) {
      expect(read(relativePath)).toMatch(/status: template.*missing.*blocks/is);
    }
  });
});

// ─── S-009 AC-5b: planner post-integration deploy handoff (caller wiring) ────

describe("infra-engineer — S-009 AC-5b: planner deploy handoff", () => {
  for (const relativePath of PLANNER_VARIANTS) {
    it(`${relativePath} exists`, () => {
      expect(exists(relativePath), `missing planner variant: ${relativePath}`).toBe(true);
    });

    it(`${relativePath} names infra-engineer as the post-integration deploy owner`, () => {
      const content = read(relativePath);
      expect(
        /infra-engineer/i.test(content),
        `${relativePath} does not reference infra-engineer`,
      ).toBe(true);
      expect(
        /post-integration deploy|deploy handoff/i.test(content),
        `${relativePath} does not describe a post-integration deploy handoff`,
      ).toBe(true);
    });

    it(`${relativePath} makes the handoff conditional on infra/deploy scope`, () => {
      const content = read(relativePath);
      expect(
        /conditional|only when|when the merged scope/i.test(content),
        `${relativePath} does not use conditional language for the deploy handoff`,
      ).toBe(true);
    });

    it(`${relativePath} forbids planner from running platform/deploy commands itself`, () => {
      const content = read(relativePath);
      expect(
        /never invokes .*deploy\.sh|MUST .*hand the deploy off|rather than running any platform/i.test(
          content,
        ),
        `${relativePath} does not forbid planner from running deploy commands directly`,
      ).toBe(true);
    });
  }
});

// ─── S-009 AC-5: deploy-ops and templates registered in docs/registries ──────

describe("infra-engineer — S-009 AC-5: deploy-ops registry parity", () => {
  for (const relativePath of REGISTRY_FILES) {
    it(`${relativePath} registers deploy-ops`, () => {
      expect(exists(relativePath), `missing registry file: ${relativePath}`).toBe(true);
      expect(
        /deploy-ops/.test(read(relativePath)),
        `${relativePath} does not register the deploy-ops skill`,
      ).toBe(true);
    });
  }

  it("technical-guidelines lists the canonical deploy/release script names", () => {
    const content = read("docs/technical-guidelines.md");
    for (const script of ["deploy", "deploy:rollback", "release"]) {
      expect(
        new RegExp(`\`${script.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\``).test(content),
        `technical-guidelines.md does not list the \`${script}\` canonical script`,
      ).toBe(true);
    }
  });

  it("system-overview skill count reconciles to twenty-six", () => {
    expect(
      /twenty-six skills/.test(read("docs/system-overview.md")),
      "system-overview.md skill count was not reconciled to twenty-six (deploy-ops added, activity-contract-validation retired per ADR-007)",
    ).toBe(true);
  });
});

// ─── S-010 AC-1..AC-7, AC-9: caller wiring and reverse-direction ─────────────
//
// Modeled on the `AC-6: Callers wired with conditional triggers` block in
// test/unit/researcher-parity.test.ts. Every caller file must reference
// infra-engineer AND use conditional-routing language, across all three trees.

/** Caller files, grouped by agent, that must route to infra-engineer. */
const S010_CALLER_FILES = {
  // `.claude/commands/developer.md` is intentionally excluded: per issue #173
  // it is a thin wrapper that points at `.claude/agents/developer.md` rather
  // than restating the contract. See test/unit/developer-command-collapse.test.ts
  // for the checks that apply to the command file specifically.
  developer: [
    ".github/agents/developer.agent.md",
    ".kiro/agents/developer.md",
    ".claude/agents/developer.md",
  ],
  implement: [
    ".claude/skills/implement/SKILL.md",
    ".github/instructions/implement.instructions.md",
    ".kiro/steering/implement.md",
  ],
  housekeeping: [
    ".github/agents/housekeeping.agent.md",
    ".kiro/agents/housekeeping.md",
    ".claude/agents/housekeeping.md",
  ],
  planner: [
    ".github/agents/planner.agent.md",
    ".kiro/agents/planner.md",
    ".claude/commands/planner.md",
  ],
  productEngineer: [
    ".github/agents/product-engineer.agent.md",
    ".kiro/agents/product-engineer.md",
    ".claude/commands/product-engineer.md",
  ],
  githubOps: [
    ".github/agents/github-ops.agent.md",
    ".kiro/agents/github-ops.md",
    ".claude/agents/github-ops.md",
  ],
} as const;

/** Conditional-routing language, mirroring the researcher AC-6 pattern. */
const CONDITIONAL_PATTERN = /conditional|recommended|SHOULD|optional|when|only when|if the/i;

// AC-9: every caller references infra-engineer with conditional language.
for (const [caller, files] of Object.entries(S010_CALLER_FILES)) {
  describe(`infra-engineer — S-010 AC-9: ${caller} caller wiring`, () => {
    for (const relativePath of files) {
      it(`${relativePath} exists`, () => {
        expect(exists(relativePath), `caller file missing: ${relativePath}`).toBe(true);
      });

      it(`${relativePath} references infra-engineer`, () => {
        expect(
          /infra-engineer/i.test(read(relativePath)),
          `${relativePath} does not reference infra-engineer`,
        ).toBe(true);
      });

      it(`${relativePath} uses conditional-routing language`, () => {
        expect(
          CONDITIONAL_PATTERN.test(read(relativePath)),
          `${relativePath} does not use conditional-routing language for infra-engineer`,
        ).toBe(true);
      });
    }
  });
}

// AC-1: developer forbids platform write commands and names routed sub-task kinds.
describe("infra-engineer — S-010 AC-1: developer platform-write prohibition", () => {
  for (const relativePath of S010_CALLER_FILES.developer) {
    it(`${relativePath} forbids emitting or executing a platform write command`, () => {
      const content = read(relativePath);
      expect(
        /MUST NOT.*(emit|execute|run).*(platform write|aws|flyctl|supabase|cloudflare)/is.test(
          content,
        ),
        `${relativePath} does not forbid platform write commands`,
      ).toBe(true);
    });

    it(`${relativePath} names the routed sub-task kinds`, () => {
      const content = read(relativePath);
      for (const kind of [
        /secrets?/i,
        /deploy/i,
        /DNS/i,
        /certificate/i,
        /IAM policy/i,
        /migration/i,
      ]) {
        expect(kind.test(content), `${relativePath} does not name routed kind ${kind}`).toBe(true);
      }
    });

    it(`${relativePath} narrows the rule 19 infrastructure/config exemption`, () => {
      const content = read(relativePath);
      expect(
        /purely infrastructure\/config/i.test(content) &&
          /(no testable behavior|not?.*licen[cs]e|does not (cover|extend|permit)|excludes? platform writes)/i.test(
            content,
          ),
        `${relativePath} does not narrow rule 19's infrastructure/config exemption`,
      ).toBe(true);
    });
  }
});

// AC-3: housekeeping lists the infra paths as never-touch (negative assertion).
describe("infra-engineer — S-010 AC-3: housekeeping never-touch infra paths", () => {
  const NEVER_TOUCH = [
    /infra\//,
    /\.github\/workflows\/deploy-\*\.yml|deploy-\*\.yml/,
    /rollback\.yml/,
    /templates\/scripts\//,
    /templates\/workflows\//,
  ];
  for (const relativePath of S010_CALLER_FILES.housekeeping) {
    for (const path of NEVER_TOUCH) {
      it(`${relativePath} lists ${path} as never-touch`, () => {
        expect(
          path.test(read(relativePath)),
          `${relativePath} does not list ${path} in its Never touch table`,
        ).toBe(true);
      });
    }
  }
});

// AC-6: github-ops documents the change-record draft PR shape.
describe("infra-engineer — S-010 AC-6: github-ops change-record PR shape", () => {
  for (const relativePath of S010_CALLER_FILES.githubOps) {
    it(`${relativePath} documents the ChangeId-cited change-record PR shape`, () => {
      const content = read(relativePath);
      expect(
        /ChangeId/i.test(content),
        `${relativePath} does not cite the ChangeId in the change-record PR shape`,
      ).toBe(true);
      expect(
        /title prefix|prefix.*title/i.test(content),
        `${relativePath} does not document the change-record title prefix`,
      ).toBe(true);
      expect(
        /label/i.test(content),
        `${relativePath} does not document the change-record label`,
      ).toBe(true);
    });
  }
});

// AC-7: infra-engineer reverse-direction — researcher (conditional) + verifier stance.
describe("infra-engineer — S-010 AC-7: reverse-direction routing", () => {
  for (const relativePath of AGENT_VARIANTS) {
    it(`${relativePath} conditionally invokes researcher for unfamiliar platform surface`, () => {
      const content = read(relativePath);
      expect(
        /researcher/i.test(content) && CONDITIONAL_PATTERN.test(content),
        `${relativePath} does not conditionally invoke researcher`,
      ).toBe(true);
    });

    it(`${relativePath} states whether a verifier audit applies to infra/ deliverables`, () => {
      const content = read(relativePath);
      expect(
        /verifier/i.test(content) && /infra\//.test(content),
        `${relativePath} does not state the verifier-audit stance for infra/ deliverables`,
      ).toBe(true);
    });
  }
});

// AC-8: workflow-chains.md gains the Infrastructure Change chain and conditional handoffs.
describe("infra-engineer — S-010 AC-8: workflow-chains headings", () => {
  const CHAINS = "docs/workflow-chains.md";

  it("adds an Infrastructure Change chain heading", () => {
    expect(
      /Infrastructure Change/i.test(read(CHAINS)),
      "docs/workflow-chains.md has no Infrastructure Change chain heading",
    ).toBe(true);
  });

  it("shows the infra lifecycle steps in the chain", () => {
    const content = read(CHAINS);
    expect(
      /discover.*plan.*approv.*apply.*verify.*record.*draft PR/is.test(content),
      "docs/workflow-chains.md Infrastructure Change chain omits lifecycle steps",
    ).toBe(true);
  });

  it("adds the conditional infra handoff to the Full Feature and Single GitHub Issue chains", () => {
    const content = read(CHAINS);
    expect(
      /Full Feature/i.test(content) && /Single GitHub Issue/i.test(content),
      "docs/workflow-chains.md is missing the Full Feature or Single GitHub Issue chain",
    ).toBe(true);
    expect(
      /conditional.*infra|infra.*conditional|infra-engineer.*when|when.*infra-engineer/is.test(
        content,
      ),
      "docs/workflow-chains.md does not show a conditional infra handoff in the existing chains",
    ).toBe(true);
  });
});

// ─── S-010 edge cases (Task 10.10) ───────────────────────────────────────────
//
// 1. An infra-shaped but local-only sub-task (e.g. a .env.example edit) stays
//    with developer — the routing rule carves it out explicitly.
// 2. A story with no infra scope invokes nothing — routing is conditional.
// 3. A housekeeping run over a repo whose deploy workflow has a lint error
//    leaves it alone — the never-touch rule is unconditional.

describe("infra-engineer — S-010 edge case: local-only infra stays with developer", () => {
  const DEVELOPER_AND_IMPLEMENT = [...S010_CALLER_FILES.developer, ...S010_CALLER_FILES.implement];
  for (const relativePath of DEVELOPER_AND_IMPLEMENT) {
    it(`${relativePath} carves out local-only .env.example edits`, () => {
      const content = read(relativePath);
      expect(
        /\.env\.example/i.test(content),
        `${relativePath} does not carve out a local-only .env.example edit from platform-write routing`,
      ).toBe(true);
    });
  }
});

describe("infra-engineer — S-010 edge case: no-infra-scope invokes nothing", () => {
  const CONDITIONAL_CALLERS = [
    ...S010_CALLER_FILES.developer,
    ...S010_CALLER_FILES.implement,
    ...S010_CALLER_FILES.planner,
    ...S010_CALLER_FILES.productEngineer,
  ];
  for (const relativePath of CONDITIONAL_CALLERS) {
    it(`${relativePath} states the routing is conditional / never mandatory`, () => {
      const content = read(relativePath);
      expect(
        /never mandatory|no infra scope|invokes nothing|invokes .*for nothing|conditional/i.test(
          content,
        ),
        `${relativePath} does not state that infra routing is conditional`,
      ).toBe(true);
    });
  }
});

describe("infra-engineer — S-010 edge case: housekeeping leaves deploy workflows alone", () => {
  for (const relativePath of S010_CALLER_FILES.housekeeping) {
    it(`${relativePath} refuses to fix a lint error in a deploy workflow`, () => {
      const content = read(relativePath);
      expect(
        /lint or formatting error|even to fix|leave (them|the file)|even when a deploy workflow/i.test(
          content,
        ),
        `${relativePath} does not state it leaves lint-erroring deploy workflows alone`,
      ).toBe(true);
    });
  }
});
