/**
 * Structural and behavioral parity checks for the infra-engineer agent.
 *
 * Covers Story S-001 and the file-contract portions of AC-1 through AC-15.
 * The platform variants intentionally share policy language while retaining
 * native frontmatter and entry-point conventions.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "../..");

const COPILOT_AGENT = ".github/agents/infra-engineer.agent.md";
const CLAUDE_AGENT = ".claude/commands/infra-engineer.md";
const KIRO_AGENT = ".kiro/agents/infra-engineer.md";
const COPILOT_ENTRY = ".github/prompts/infra-engineer.prompt.md";
const TEMPLATE = "templates/infra/environments.yaml";

const AGENT_VARIANTS = [COPILOT_AGENT, CLAUDE_AGENT, KIRO_AGENT] as const;
const REQUIRED_FILES = [...AGENT_VARIANTS, COPILOT_ENTRY, TEMPLATE] as const;

/** Normative policy statements required in every platform variant. */
const CONTRACT_STATEMENTS: ReadonlyArray<{ label: string; pattern: RegExp }> = [
  {
    label: "working loop",
    pattern:
      /discover\s*[→>-]\s*plan.*approve plan.*approve step.*backup.*apply.*verify.*record.*result/is,
  },
  { label: "no skippable phase", pattern: /no skippable phase/i },
  { label: "ChangeId and per-step approval", pattern: /ChangeId.*per-step approval/is },
  {
    label: "no autonomous or batch mode",
    pattern: /no autonomous.*batch mode|no batch.*autonomous mode/is,
  },
  {
    label: "step schema",
    pattern: /kind.*tool.*environment.*forward.*expected result.*verify.*revert.*touches state/is,
  },
  {
    label: "step state machine",
    pattern: /pending.*approved.*backed_up.*applied.*verified.*failed.*reverted.*skipped/is,
  },
  {
    label: "production revert rule",
    pattern: /production.*revert.*refused|production.*no revert.*refus/i,
  },
  { label: "rollback reverse order", pattern: /rollback\.sh.*reverse order/i },
  {
    label: "production backup rule",
    pattern: /production.*touches state.*backup id.*restore command/is,
  },
  { label: "two-tier model", pattern: /foundation.*application.*tier0_tool/is },
  { label: "ephemeral ExpiresAt", pattern: /ephemeral.*ExpiresAt/is },
  {
    label: "destroy safeguards",
    pattern: /destroy.*reverse order.*typed.*environment.*production.*foundation.*refus/is,
  },
  { label: "identity assertion", pattern: /identity.*assert|assert.*identity/is },
  {
    label: "platform identity probes",
    pattern: /sts get-caller-identity.*flyctl auth whoami.*supabase projects list/is,
  },
  { label: "tool checks", pattern: /presence.*version floor.*authentication.*remediation/is },
  { label: "no auto-install or fallback", pattern: /no auto-install.*no fallback/is },
  { label: "tool-routing table", pattern: /tool-routing table/is },
  { label: "cost rule", pattern: /monthly estimate.*source.*APPROVAL REQUIRED/is },
  { label: "read-only cost sweep", pattern: /read-only cost sweep/is },
  { label: "plan record", pattern: /plan\.md.*ChangeId.*environment.*identity/is },
  { label: "commands record", pattern: /commands\.sh.*append-only/is },
  {
    label: "result and inventory records",
    pattern: /result\.md.*_generated.*generated by infra-engineer/is,
  },
  { label: "draft PR handoff", pattern: /draft PR.*github-ops.*never merged/is },
  { label: "tag prohibition", pattern: /never.*create.*move.*delete.*push.*tags/is },
  {
    label: "secret handling",
    pattern: /ARN.*fly secrets.*supabase secrets.*gh secret set.*OIDC/is,
  },
  {
    label: "bounded redacted log triage",
    pattern: /bounded.*UTC.*redaction.*inference.*labelled/is,
  },
  {
    label: "Cloudflare DNS and certificates",
    pattern: /Cloudflare.*DNS.*certificate.*prior.*revert/is,
  },
  { label: "template-status block", pattern: /status: template.*missing.*blocks/is },
];

function exists(relativePath: string): boolean {
  return existsSync(resolve(ROOT, relativePath));
}

function read(relativePath: string): string {
  return readFileSync(resolve(ROOT, relativePath), "utf8");
}

function extractFrontmatter(contents: string): string | null {
  if (!contents.startsWith("---\n")) return null;
  const end = contents.indexOf("\n---", 4);
  return end === -1 ? null : contents.slice(4, end + 1);
}

describe("infra-engineer — required files and packaging", () => {
  for (const relativePath of REQUIRED_FILES) {
    it(`ships ${relativePath}`, () => {
      expect(exists(relativePath), `missing required file: ${relativePath}`).toBe(true);
    });
  }

  it("keeps all platform variants non-empty", () => {
    for (const relativePath of AGENT_VARIANTS) {
      expect(read(relativePath).trim(), `${relativePath} is empty`).not.toBe("");
    }
  });

  it("does not ship a Claude agent duplicate", () => {
    expect(exists(".claude/agents/infra-engineer.md")).toBe(false);
  });
});

describe("infra-engineer — behavioral parity", () => {
  for (const statement of CONTRACT_STATEMENTS) {
    it(`declares ${statement.label} in all variants`, () => {
      const missing = AGENT_VARIANTS.filter(
        (relativePath) => !exists(relativePath) || !statement.pattern.test(read(relativePath)),
      );
      expect(
        missing,
        `contract statement "${statement.label}" absent from: ${missing.join(", ")}`,
      ).toEqual([]);
    });
  }
});

describe("infra-engineer — Kiro frontmatter", () => {
  it("declares description, tools, and resources without permissions", () => {
    const frontmatter = extractFrontmatter(read(KIRO_AGENT));
    expect(frontmatter, `${KIRO_AGENT} has no frontmatter`).not.toBeNull();
    expect(frontmatter).toMatch(/^description:/m);
    expect(frontmatter).toMatch(/^tools:\s*\[read, write, shell\]/m);
    expect(frontmatter).toMatch(/^resources:/m);
    expect(frontmatter).not.toMatch(/^permissions:/m);
  });
});

describe("infra-engineer — template status guard", () => {
  it("starts the environment template with the status sentinel", () => {
    expect(read(TEMPLATE).split("\n", 1)[0]).toBe("# status: template");
  });

  it("states that a template-status file blocks work", () => {
    for (const relativePath of AGENT_VARIANTS) {
      expect(read(relativePath)).toMatch(/status: template.*missing.*blocks/is);
    }
  });
});
